version: '2'

services:
  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=nlp
      - MONGO_INITDB_ROOT_USERNAME=nlp
      - MONGO_INITDB_ROOT_PASSWORD=nlp123
    networks:
      - nlp-network
  tika:
    image: 'apache/tika:1.24-full'
    ports:
      - '9998:9998'
    container_name: tika-server-ocr
    networks:
      - nlp-network
  nlp:
    image: 'docker.io/library/nlp:0.0.1-SNAPSHOT'
    ports:
      - '8080:8080'
      - '80:80'
    container_name: ocr-app
    links:
      - tika
      - mongo
    networks:
      - nlp-network
networks:
  nlp-network:
    driver: bridge